# Generated by Django 4.1 on 2023-12-04 17:02

from django.db import migrations, models
import voting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(validators=[voting.validators.validador_palabras_ofensivas]),
        ),
        migrations.AlterField(
            model_name='voting',
            name='desc',
            field=models.TextField(blank=True, null=True, validators=[voting.validators.validador_palabras_ofensivas]),
        ),
    ]
