# Generated by Django 4.1 on 2023-12-04 17:47

from django.db import migrations, models
import voting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_question_desc_alter_voting_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(validators=[voting.validators.validador_palabras_ofensivas]),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=200, validators=[voting.validators.validador_palabras_ofensivas]),
        ),
    ]
