# Generated by Django 4.1 on 2023-12-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_questionoption_option_alter_voting_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('solution', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id',)},
            },
        ),
        migrations.CreateModel(
            name='Apportionment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('method', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id', 'seats', 'method')},
            },
        ),
    ]
