# Generated by Django 4.1 on 2023-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apportionment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('method', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id', 'seats', 'method')},
            },
        ),
    ]
