# Generated by Django 4.1 on 2023-12-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField()),
                ('solution', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id',)},
            },
        ),
    ]
