# Generated by Django 4.1 on 2023-12-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
