# Generated by Django 4.1 on 2023-12-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='ejemplo@email.com', max_length=50),
        ),
    ]
